### ISSUE TITLE
Check Flickr images consumption

### ISSUE THREAD

**Issue by danipilze** [SIB-Colombia/CBC#4]
It seems Flickr images are not well consumed.

@daiesco reports that this sheet http://biodiversidad.co/fichas/4760 should show this picture https://www.flickr.com/photos/inst_humboldt/17626248423/

for this specific sheet it seems is due to an un-match of scientific names, but for the rest of sheets it needs a review anyway

**Comment by mcubillos** [comment]
This is because extrenal-images-feeder only consumes from https://www.flickr.com/groups/2287605@N22/
